#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
	    # Send SIGTERM signal to stop the process
	        kill "$pid"
		    echo "Terminated"
	    else
		        echo "Process is not running"
fi
