#!/usr/bin/env bash
# This script stops the 7-highlander process

# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send SIGTERM signal to stop the process gracefully
    kill -SIGTERM "$pid"
else
    echo "Process is not running"
fi
