#!/usr/bin/env bash
# This script kills the 7-highlander process

# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send SIGKILL signal to forcefully stop the process
    kill -9 "$pid"
else
    echo "Process is not running"
fi
