#!/usr/bin/env bash
# This script displays specific information from the /etc/passwd file

while IFS=':' read -r username x uid gid gecos homedir shell; do
    echo "$username:$uid:$homedir"
done </etc/passwd
