#!/usr/bin/env bash
# This script changes the IP addresses for localhost and facebook.com

# Configure localhost to resolve to 127.0.0.2
sudo sed -i 's/127\.0\.0\.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
sudo sed -i 's/[0-9.]*\s*facebook.com/8.8.8.8 facebook.com/' /etc/hosts
