#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to get IPv4 addresses and filter out loopback addresses
ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | awk '{print $2}'
